### ISSUE TITLE
Total pulls count

### ISSUE THREAD

**Issue by kroese** [eggplants/ghcr-badge#72] opened 2023-04-29 23:50 UTC
It would be nice to have a badge that display the total pulls count, like is possible with Dockerhub badges. I dont know if GHCR provides this information, or that it is only available per image. In that case the badge would need to sum up all values, but that might be too resource-intensive.

**Comment by eggplants** [comment] 2023-05-01 10:29
It can be fetched with not Docker Registry API
but GitHub GraphQL API.

https://docs.github.com/en/graphql/reference/objects#packagestatistics

https://docs.github.com/en/graphql/reference/objects#packageversionstatistics

But I think it is out of scope this badge service for now. If you want to use this feature, please send your PR. I'll welcome.

**Comment by zhilyaev** [comment] 2023-06-17 12:54
This will be awesome!

**Comment by razonyang** [comment] 2023-07-19 09:27
+1 for this feature, most of the users of my images prefer to use GHCR than Docker Hub, the number of downloads is almost surpassing Docker Hub's.

**Comment by eggplants** [comment] 2023-08-04 18:01
> It can be fetched with not Docker Registry API
> but GitHub GraphQL API.
> 
> https://docs.github.com/en/graphql/reference/objects#packagestatistics
> 
> https://docs.github.com/en/graphql/reference/objects#packageversionstatistics

GraphQL Query for repo packages seems dead due to deprecation.
https://github.blog/changelog/2022-08-18-deprecation-notice-graphql-for-packages/

And I confirmed these queries are currently not working.

![image](https://github.com/eggplants/ghcr-badge/assets/42153744/2a7fa888-5c00-48a8-82ea-c0c498dd25b6)

Sadly, there does not seem to be a replacement for `PackageVersionStatistics` in the REST API.
https://docs.github.com/en/free-pro-team@latest/rest/packages/packages?apiVersion=2022-11-28

**Comment by razonyang** [comment] 2023-12-14 06:00
What about  parsing HTML other than API as a provisional solution?

**Closed as completed** 2024-06-20 07:56 UTC
Labels: enhancement
